import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
const browser = await chromium.launch({headless: true});
const page = await browser.newPage({viewport: {width: 1440, height: 1100}, colorScheme: 'dark'});
page.setDefaultTimeout(12000);
const errors = [];
page.on('pageerror', e => errors.push(e.message));
const output = '/tmp/kenkui-prototype-check';
await mkdir(output, {recursive: true});
try {
  await page.clock.install();
  await page.goto('http://127.0.0.1:5174/prototype/');
  await page.getByRole('button', {name: 'Reset demo', exact: true}).click();
  await page.getByRole('button', {name: 'Try a sample book'}).click();
  await page.getByLabel('Title', {exact: true}).fill('The Secret Garden — my edition');
  await page.locator('input[type=file][accept="image/png,image/jpeg,image/webp"]').setInputFiles({name: 'cover.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=', 'base64')});
  await page.getByRole('button', {name: 'Remove cover'}).click();
  assert.match(await page.getByTestId('quote').innerText(), /126 credits/);
  await page.getByText('Advanced', {exact: true}).click();
  await page.getByLabel('Chapters', {exact: true}).selectOption('First chapter only');
  assert.match(await page.getByTestId('quote').innerText(), /5 credits/);
  await page.getByLabel('Chapters', {exact: true}).selectOption('All chapters');
  await page.getByRole('button', {name: 'Continue', exact: true}).click();
  assert.equal(await page.getByRole('button', {name: 'Preview Clara', exact: true}).count(), 0, 'No duplicated audition on the book screen');
  await page.getByRole('button', {name: 'Change voice', exact: true}).click();
  await page.getByRole('dialog').getByRole('button', {name: 'Preview Clara', exact: true}).click();
  await page.getByRole('button', {name: 'Pause Clara', exact: true}).waitFor();
  const heights = () => page.locator('.voice-dialog .wave i').evaluateAll(bars => bars.map(b => b.style.transform));
  await page.waitForFunction(() => [...document.querySelectorAll('.voice-dialog .wave i')].some(b => Number(b.style.transform.match(/[\d.]+/)?.[0]) > .2), {timeout: 6000});
  const frame1 = await heights();
  await page.waitForTimeout(160);
  const frame2 = await heights();
  assert.notDeepEqual(frame1, frame2, 'Wave follows real analyser levels');
  assert.ok(new Set(frame2).size > 2, 'Frequency buckets have independent levels');
  await page.getByRole('button', {name: 'Preview Sterling', exact: true}).click();
  await page.getByRole('button', {name: 'Pause Sterling', exact: true}).waitFor();
  assert.equal(await page.getByRole('button', {name: 'Pause Clara', exact: true}).count(), 0);
  await page.getByRole('button', {name: 'Sterling British', exact: false}).click();
  await page.getByRole('button', {name: 'Use Sterling', exact: true}).click();
  assert.match(await page.getByTestId('quote').innerText(), /126 credits/);
  await page.getByRole('button', {name: 'Full cast Narrator', exact: false}).click();
  assert.match(await page.getByTestId('quote').innerText(), /189 credits/);
  await page.getByRole('button', {name: 'Change voice for Mrs. Bennet', exact: true}).click();
  await page.getByRole('button', {name: 'Mabel English Yorkshire', exact: false}).click();
  await page.getByRole('button', {name: 'Use Mabel', exact: true}).click();
  await page.getByRole('button', {name: 'Single narrator One', exact: false}).click();
  assert.equal(await page.getByRole('button', {name: 'Change voice for Mrs. Bennet', exact: true}).count(), 0);
  await page.getByRole('button', {name: 'Full cast Narrator', exact: false}).click();
  assert.match(await page.locator('.cast-list').innerText(), /Mabel/);
  await page.screenshot({path: `${output}/desktop-cast.png`, fullPage: true});
  await page.reload();
  await page.getByRole('button', {name: 'The Secret Garden — my edition — Draft, open actions', exact: true}).click();
  await page.getByRole('button', {name: 'Continue setup', exact: true}).click();
  assert.match(await page.locator('.cast-list').innerText(), /Mabel/);
  await page.getByRole('button', {name: 'Continue', exact: true}).click();
  await page.getByRole('button', {name: 'Play example scene', exact: true}).click();
  await page.getByRole('button', {name: 'Pause example scene', exact: true}).waitFor();
  await page.getByRole('group', {name: 'Example scene narration'}).getByRole('button', {name: 'Single narrator', exact: true}).click();
  await page.getByRole('button', {name: 'Pause example scene', exact: true}).waitFor();
  await page.getByRole('button', {name: 'Pause example scene', exact: true}).click();
  assert.match(await page.getByTestId('quote').innerText(), /189 credits/, 'Example mode does not mutate book mode or price');
  assert.ok(await page.getByRole('button', {name: 'Create · 189 credits'}).isDisabled());
  await page.getByRole('button', {name: 'Add credits', exact: true}).click();
  await page.getByRole('heading', {name: 'Credits & billing'}).waitFor();
  await page.screenshot({path: `${output}/desktop-billing.png`, fullPage: true});
  await page.getByRole('button', {name: '500 credits $5.00', exact: false}).click();
  await page.getByRole('button', {name: 'Add 500 demo credits', exact: true}).click();
  await page.getByRole('button', {name: 'Back to your book', exact: false}).click();
  await page.getByRole('button', {name: 'Create · 189 credits'}).click();
  await page.getByRole('heading', {name: 'Bringing your book to life', exact: true}).waitFor();
  await page.getByRole('button', {name: 'Billing, 461 demo credits', exact: true}).waitFor();
  await page.getByRole('button', {name: 'Cancel conversion', exact: true}).click();
  await page.getByRole('button', {name: 'Billing, 650 demo credits', exact: true}).waitFor();
  const persisted = await page.evaluate(() => JSON.parse(localStorage.getItem('kenkui-prototype-v2')));
  assert.equal(persisted.ledger[0].credits, 189);
  await page.getByRole('button', {name: 'Create · 189 credits'}).click();
  await page.clock.runFor(62000);
  await page.getByRole('heading', {name: 'Your audiobook is ready', exact: true}).waitFor();
  await page.getByRole('button', {name: 'Billing, 461 demo credits', exact: true}).waitFor();
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('link', {name: 'Download example', exact: false}).click();
  assert.equal((await downloadEvent).suggestedFilename(), 'kenkui-example-scene.wav');
  await page.clock.resume();
  for (const width of [390, 320, 768]) {
    await page.setViewportSize({width, height: 844});
    await page.getByRole('button', {name: 'Kenkui Studio home', exact: true}).click();
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Home overflow ${width}`);
    await page.getByRole('button', {name: 'Try a sample book'}).click();
    await page.getByRole('button', {name: 'Continue', exact: true}).click();
    await page.getByRole('button', {name: 'Full cast Narrator', exact: false}).click();
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Cast overflow ${width}`);
    await page.getByRole('button', {name: 'Change voice for Mrs. Bennet'}).click();
    await page.getByLabel('Search voices').fill('no matching voice');
    await page.getByText('No voices match. Try another name or accent.', {exact: true}).waitFor();
    await page.getByLabel('Search voices').fill('');
    await page.keyboard.press('Escape');
    await page.getByLabel('Appearance').selectOption('light');
    await page.waitForTimeout(400);
    await page.screenshot({path: `${output}/light-cast-${width}.png`, fullPage: true});
    await page.getByRole('button', {name: 'Continue', exact: true}).click();
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Review overflow ${width}`);
    await page.getByRole('button', {name: 'Add credits', exact: true}).click();
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Billing overflow ${width}`);
    await page.screenshot({path: `${output}/billing-${width}.png`, fullPage: true});
  }
  await page.getByRole('button', {name: 'Back to your book', exact: false}).click();
  await page.getByRole('button', {name: 'Back', exact: true}).click();
  await page.getByRole('button', {name: 'Change voice', exact: true}).click();
  await page.emulateMedia({reducedMotion: 'reduce'});
  await page.getByRole('dialog').getByRole('button', {name: 'Preview Clara', exact: true}).click();
  await page.getByRole('button', {name: 'Pause Clara', exact: true}).waitFor();
  assert.ok((await heights()).every(h => h === 'scaleY(0.16)'), 'Reduced motion keeps bars static');
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('.wave.speaking').count(), 0);
  assert.deepEqual(errors, []);
  console.log('PASS: audio-driven wave, exclusive playback, reduced motion, single/full-cast preservation, scene playback, dynamic credits, billing/top-up, reservation/refund/completion, downloads, draft restore, cover upload, and responsive layouts.');
} catch (e) {
  await page.screenshot({path: `${output}/failure.png`, fullPage: true});
  console.error(await page.locator('body').innerText());
  throw e;
} finally {await browser.close();}
